Spring tests
Zel1oy/online-book-store pull request #11
Opened 2023-09-28 22:12 UTC by Zel1oy

2023-09-29 05:56 UTC, OlegTuryk reviewed
Fix conflicts

2023-10-06 13:18 UTC, Dimagaa approved these changes
Well done!

2023-10-06 13:18 UTC, Dimagaa commented on pom.xml
> +            <scope>test</scope>
Why do you need h2 database?

2023-10-06 13:18 UTC, Dimagaa commented on src/test/resources/db/cart-item-insert.sql
> +VALUES (1, 1, 1, 4, false)
Add an empty line

2023-10-06 13:18 UTC, Dimagaa commented on src/test/resources/db/shopping-cart-insert.sql
> +VALUES (1, 2, false)
Add empty line

2023-10-09 13:22 UTC, andrii-hoienko requested changes
GJ! Let`s improve your solution

2023-10-09 13:22 UTC, andrii-hoienko commented on src/test/java/com/example/onlinebookstore/controller/CategoryControllerTest.java
> +        System.out.println(expectedCategoryResponseDto);
What purpose of this?

2023-10-09 13:22 UTC, andrii-hoienko commented on src/test/java/com/example/onlinebookstore/controller/CategoryControllerTest.java
> +        assertThrows(EntityNotFoundException.class,
check error message as well

2023-10-09 13:22 UTC, andrii-hoienko commented on src/test/java/com/example/onlinebookstore/service/AuthenticationServiceTest.java
> +        verify(jwtUtil).generateToken(anyString());
Not necessary to "verify" mocks that you "when"

2023-10-09 13:22 UTC, andrii-hoienko commented on src/test/java/com/example/onlinebookstore/service/ShoppingCartServiceTest.java
> +        verify(userService, times(1)).getAuthenticatedUser();
times(1) is by default

2023-10-09 13:22 UTC, andrii-hoienko commented on src/test/resources/db/cart-item-insert.sql
> +VALUES (1, 1, 1, 4, false)
agree

2023-10-09 13:22 UTC, andrii-hoienko commented on src/test/resources/db/shopping-cart-insert.sql
> +VALUES (1, 2, false)
agree

2023-10-11 06:30 UTC, nacenik approved these changes
LGTM! :)

2023-10-11 07:01 UTC, nacenik approved these changes

2023-10-11 20:40 UTC, merged