Implemented CustomGlobalExceptionHandler and validation for dto
Zel1oy/online-book-store pull request #4
Opened 2023-09-07 21:11 UTC by Zel1oy

2023-09-08 11:26 UTC, irynamekh requested changes
Good job)

2023-09-08 11:26 UTC, irynamekh commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(
I think it is worth adding at least one more method, for example, for processing an error that occurs at the service level when an element by this identifier is missing

2023-09-08 12:17 UTC, irynamekh approved these changes

2023-09-14 07:37 UTC, nacenik requested changes
Good solution, let's improve it :)

2023-09-14 07:37 UTC, nacenik commented on pom.xml
> +            <artifactId>hibernate-validator</artifactId>
better to use starter

2023-09-14 07:37 UTC, nacenik commented on src/main/java/com/example/onlinebookstore/dto/CreateBookRequestDto.java
> +    @URL
spring could be not only URL. Commonly, an image is a byte array, so I'd recommend you validate this field on null and empty

2023-09-14 07:37 UTC, nacenik commented on src/main/java/com/example/onlinebookstore/dto/CreateBookRequestDto.java
> +    @Length(min = 1, max = 255)
Read about `Length` and `Size` annotation and choose the best one

2023-09-14 07:37 UTC, nacenik commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        notValidResponse.setErrors(new String[]{e.getMessage()});
code duplication, you can extract to the private method and reuse it

2023-09-14 15:50 UTC, vovasalyha approved these changes

2023-09-14 15:50 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/dto/ArgumentNotValidResponse.java
> +public class ArgumentNotValidResponse {
I think you can convert it to general exception response format and use this class for all handlers

2023-09-14 16:24 UTC, merged