Security
Zel1oy/online-book-store pull request #6
Opened 2023-09-12 14:05 UTC by Zel1oy

2023-09-12 21:05 UTC, keda-vlad approved these changes
GJ, only minor fixes

2023-09-12 21:05 UTC, keda-vlad commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/06-add-admin-user.yaml
add an empty line at the end

2023-09-12 21:05 UTC, keda-vlad commented on src/test/resources/application.properties
> +jwt.expiration = 300000
add an empty line at the end

2023-09-12 21:05 UTC, keda-vlad commented on src/main/resources/db/changelog/changes/06-add-admin-user.yaml
> +                  valueNumeric: 2
add an empty line at the end

2023-09-12 21:05 UTC, keda-vlad commented on src/main/resources/db/changelog/changes/05-add-roles-to-roles-table.yaml
> +                  value: ROLE_ADMIN
add an empty line at the end

2023-09-12 21:05 UTC, keda-vlad commented on src/main/resources/db/changelog/changes/04-create-user-role-table.yaml
> +                    references: roles(id)
add an empty line at the end

2023-09-12 21:05 UTC, keda-vlad commented on src/main/resources/db/changelog/changes/03-create-roles-table.yaml
> +                  constraints:
add an empty line at the end

2023-09-12 21:05 UTC, keda-vlad commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +              - column:
add an empty line at the end

2023-09-12 21:05 UTC, keda-vlad commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> -      author: Arsenii
add an empty line at the end

2023-09-14 07:49 UTC, nacenik requested changes
GJ! Let's improve your solution :)

2023-09-14 07:49 UTC, nacenik commented on pom.xml
> +            <version>3.1.3</version>
Do you really need to put a version for the starter?

2023-09-14 07:49 UTC, nacenik commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_USER')")
I am wondering if this endpoint could work for both roles even without this annotation.

2023-09-14 07:49 UTC, nacenik commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER') || hasRole('ROLE_ADMIN')")
The same here

2023-09-14 07:49 UTC, nacenik commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_USER')")
and here

2023-09-14 07:49 UTC, nacenik commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        notValidResponse.setErrors(new String[]{e.getMessage()});
As I mentioned in the previous task - code duplication

2023-09-14 07:49 UTC, nacenik commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        notValidResponse.setStatus(HttpStatus.NOT_FOUND);
I'd recommend you throw 409 instead of 404 if an exception occurs during registration

2023-09-14 07:49 UTC, nacenik commented on src/main/java/com/example/onlinebookstore/service/impl/BookServiceImpl.java
> +        isPresent(id);
do you really need this additional check?

2023-09-14 07:49 UTC, nacenik commented on src/main/java/com/example/onlinebookstore/mapper/UserMapper.java
> +    UserResponseDto toRegisterDto(User user);
```suggestion
    UserResponseDto toResponseDto(User user);
```

2023-09-14 07:49 UTC, nacenik commented on src/main/resources/db/changelog/changes/06-add-admin-user.yaml
> +                  valueNumeric: 1
use sth like this: `valueComputed: (SELECT id FROM users WHERE email = 'admin@email')`

2023-09-14 07:49 UTC, nacenik commented on src/main/resources/db/changelog/changes/06-add-admin-user.yaml
> +                  valueNumeric: 2
the same

2023-09-14 15:53 UTC, vovasalyha approved these changes

2023-09-14 16:32 UTC, merged