Added ShoppingCartController to manage ShoppingCart and items in it. …
Zel1oy/online-book-store pull request #8
Opened 2023-09-18 18:49 UTC by Zel1oy

…Provided all stuff needed

2023-09-19 01:15 UTC, IhorKalaur approved these changes

2023-09-20 12:21 UTC, andrii-hoienko requested changes
GJ, but some improvements required

2023-09-20 12:21 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/config/SecurityConfig.java
> +                                        "/swagger-ui/**", "/v3/api-docs/**", ERROR_URL)
If you created constants for AUTHORIZATION_URL please make constants for other URLs to be consistent

2023-09-20 12:21 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = new CartItem();
Move logic of creation and population to separate method

2023-09-20 12:21 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Book not found"));
add details to error message

2023-09-20 12:21 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/10-create-cart-items-table.yaml
> +                    nullable: false
Please add empty lines to the end of each file

2023-09-22 15:35 UTC, vovasalyha approved these changes

2023-09-28 22:11 UTC, merged